service:
  version:
    default:
      com.qunhe.exabrain.commoditycenterservice:default
      com.qunhe.instdeco.service.messagecenter:default

stage: dev

# sso
qunhe:
  kuauth:
    appName: cop.kujiale|owt.qa|pdl.data|service.data-diff
    switchOffReqLog: false
  tddl:
    app-name: data_diff-data_diff-dev
  search-service:
    host: http://data-search-sit.k8s-qunhe.qunhequnhe.com