service:
  version:
    default:
      com.qunhe.exabrain.commoditycenterservice:default
      com.qunhe.instdeco.service.messagecenter:default

stage: prod_test

# sso
qunhe:
  kuauth:
    appName: cop.kujiale|owt.qa|pdl.data|service.data-diff
    switchOffReqLog: false
  tddl:
    app-name: data_diff-data_diff-prod
  search-service:
    host: http://data-search-prodtest.k8s-aliyun.qunhequnhe.com