server:
  port: 80

spring:
  profiles:
    active: ${APP_STAGE:dev}
  task:
    scheduling:
      pool:
        size: 2
 # mysql
  datasource:
    url: jdbc:mysql://itest.qunhequnhe.com/material?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: material
    password: material1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 2870000
  # redis
  redis:
    redisson:
      config: classpath:redisson-config.yml
  # file-io
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



